cms/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="mostrar indice"),
    path('loggedIn', views.loggedIn, name="mostrar indice"),
    path('logout', views.logout_view, name="mostrar indice"),
    path('imagen', views.imagen, name="mostrar indice"),
    path('add/<str:llave>', views.cms_new, name="editar con django forms"),
    path('comment/<str:llave>', views.comment_new, name="editar con django forms"),
    path('<str:llave>', views.get_content, name="mostrar contenido")
]

myfirstapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('hello', views.say_hello, name='hello'),
	path('bye/<name>', views.say_bye_to, name='bye'),
	path('number/<int:number>', views.say_number, name='number')
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login

urlpatterns = [
    path('cms/', include('cms.urls')),
    path('myfirstapp/', include('myfirstapp.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view())
]

cms/models.py
from django.db import models

# Create your models here.
class Contenido(models.Model):
    clave = models.CharField(max_length=64)
    valor = models.TextField()

    def __str__(self):
        return "ID=" + str(self.id) + " --- " + self.clave + "," + self.valor

    def contiene_pagina(self):
        return ('Pagina' in self.valor)

class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete =  models.CASCADE)
    titulo = models.CharField(max_length=128)
    cuerpo = models.TextField()
    fecha = models.DateTimeField()

    def __str__(self):
        return "ID=" + str(self.id) + " --- " + self.titulo + "," + str(self.fecha) + "," + self.cuerpo + "," + str(self.contenido.id)

myfirstapp/models.py
from django.db import models

# Create your models here.

cms/forms.py
from django import forms
from .models import Contenido, Comentario

class ContentForm(forms.ModelForm):
    class Meta:
        model = Contenido
        fields = ('clave', 'valor')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('titulo', 'cuerpo')

cms/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, HttpRequest
from .models import Contenido, Comentario
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from .forms import ContentForm, CommentForm

class Counter():

    def __init__(self):
        self.count: int = 0

    def increment(self) -> int:
        self.count += 1
        return(self.count)

counter: Counter = Counter()

@csrf_exempt
def get_content(request, llave):

    if (request.method == "POST"):
        action = request.POST['action']
        if action == "Modificar contenido":
            value = request.POST['valor']
            try:
                contenido = Contenido.objects.get(clave=llave)
                contenido.valor = value
            except Contenido.DoesNotExist:
                contenido = Contenido(clave=llave, valor=value)
            contenido.save()
        elif action == "Anadir comentario":
            contenido = Contenido.objects.get(clave=llave)
            titulo = request.POST['titulo']
            cuerpo = request.POST['cuerpo']
            fecha = timezone.now()
            q = Comentario(contenido=contenido, titulo=titulo, cuerpo=cuerpo, fecha=fecha)
            q.save()
    try:
        contenido = Contenido.objects.get(clave=llave)
        context = {"contenido": contenido}
        return render(request, 'cms/content.html', context)

    except Contenido.DoesNotExist:
        context = {"llave": llave}
        return render(request, 'cms/new.html', context)


def cms_new(request, llave):
    if request.method == "POST":
        form = ContentForm(request.POST)
        if form.is_valid():
            valor = form.save()
            return redirect('mostrar contenido', llave=llave)
    form = ContentForm()
    return render(request, 'cms/add.html', {'form': form, 'is_content': True})

def comment_new(request, llave):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            content = Contenido.objects.get(clave=llave)
            comment = Comentario(contenido = content, titulo = request.POST['titulo'], cuerpo = request.POST['cuerpo'], fecha = timezone.now())
            comment.save()
            return redirect('mostrar contenido', llave=llave)
    form = CommentForm()
    return render(request, 'cms/add.html', {'form': form, 'is_content': False})

def index(request):
    content_list = Contenido.objects.all()
    template = loader.get_template('cms/index.html')
    context = {
        'content_list': content_list
    }
    return HttpResponse(template.render(context, request))

def loggedIn(request):
    if request.user.is_authenticated:
        respuesta = "Logueado como " + request.user.username
    else:
        respuesta = "No estas logueado :( Puedes hacerlo aqui: <a href='/login'>Loguéame</a>"

    return HttpResponse(respuesta)

def logout_view(request):
    logout(request)
    return redirect("/cms/")

def imagen(request):
    template = loader.get_template('cms/plantilla.html')
    context = {}
    return HttpResponse(template.render(context, request))

myfirstapp/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse

def index(request):
	return HttpResponse('<h1>Welcome to my App!</h1>')

def say_hello(request):
	return HttpResponse('Hello!')

def say_bye_to(request, name):
	return HttpResponse('Bye %s'%name)

def say_number(request, number=0):
	return HttpResponse('Number: %s'%number)
	

cms/templates/cms/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if is_content %}
        <h2>Anadir contenido</h2>
    {% else %}
        <h2>Anadir comentario</h2>
    {% endif %}

  <form method = "POST">
    {% csrf_token %}
    <table>
      {{ form }}
    </table>
    <button type = "submit">Guardar datos</button>
  </form>
</body>
</html>

cms/templates/cms/content.html
{% extends 'cms/schema.html' %}

{% block cuerpo %}
    <p>
    La llave solicitada es: {{ contenido.clave }}
    <br>
    El valor de la llave es: {{ contenido.valor }}
    </p>

    {% for comentario in contenido.comentario_set.all %}
    <p><b>Titulo</b>: {{ comentario.titulo }}
    <br><b>Cuerpo</b>: {{ comentario.cuerpo }}
    <br><b>Fecha</b>: {{ comentario.fecha }}</p>
    {% endfor %}
    <br>
    <br>

    <form action="" method="POST">
    Introduce el valor: <input type="text" name="valor">
    <br>
    <input type="submit" name="action" value="Modificar contenido">
    </form>

    <form action="" method="POST">
    <br>Titulo: <input type = "text" name = "titulo">
    <br>Cuerpo: <input type = "text" name = "cuerpo">
    <br><input type="submit" name="action" value="Anadir comentario">
    </form>
{% endblock %}

cms/templates/cms/new.html
{% extends 'cms/schema.html' %}

{% block cuerpo %}
    {% if request.user.is_authenticated %}

        Hola, la llave solicitada es: {{ llave }} pero no existe en la base de datos.

        <form action="" method="POST">
        Introduce el valor: <input type="text" name="valor">
        <br>
        <input type="submit" name="action" value="Modificar contenido">
        </form>

    {% else %}

        No estas logueado :( Puedes hacerlo aqui: <a href='/login'>Loguéame</a>

    {% endif %}
{% endblock %}

cms/templates/cms/plantilla.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load static %}
    <img src="{% static 'cms/URJC_logo.svg' %}" width="200" height="100">
</body>
</html>

cms/templates/cms/schema.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block primero %}
    {% if request.user.is_authenticated %}

        Hola, estas autenticado como {{ request.user.user_name }}. Bienvenido.

    {% else %}

        No estas logueado :( Puedes hacerlo aqui: <a href='/login'>Loguéame</a>

    {% endif %}
{% endblock %}

{% block cuerpo %}
    Aqui vendria el cuerpo
{% endblock %}

    {% load static %}
    <img src="{% static 'cms/URJC_logo.svg' %}" width="200" height="100">

</body>
</html>

templates/cms/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Este es el titulo de mi web</title>
</head>
<body>
{% if content_list %}
<ul>
    {% for content in content_list %}
    <li><a href="{{ content.clave }}"> {{ content.clave }}</a> <--> {{ content.id }} <--> {{ content.valor}}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>